{"trial_id": "0072", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "activation", "default": "relu", "conditions": [], "values": ["relu", "tanh", "sigmoid", "elu", "selu", "softmax"], "ordered": false}}, {"class_name": "Int", "config": {"name": "first_units", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 6, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_2", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_3", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_4", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_5", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}], "values": {"activation": "relu", "first_units": 1, "num_layers": 2, "units_0": 7, "units_1": 9, "units_2": 9, "units_3": 1, "units_4": 7, "units_5": 9, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 4, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 53, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node adam/Mul_23 defined at (most recent call last):\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/runpy.py\", line 86, in _run_code\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 195, in start\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/asyncio/events.py\", line 80, in _run\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 359, in execute_request\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 446, in do_execute\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n\n  File \"/var/folders/37/thnn_5j55qz9llgp681b9w_m0000gn/T/ipykernel_38615/1874305172.py\", line 2, in <module>\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 314, in fit\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 117, in one_step_on_iterator\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 104, in one_step_on_data\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 69, in train_step\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/optimizers/base_optimizer.py\", line 282, in apply_gradients\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/optimizers/base_optimizer.py\", line 351, in apply\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/optimizers/base_optimizer.py\", line 405, in _backend_apply_gradients\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/backend/tensorflow/optimizer.py\", line 119, in _backend_update_step\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/backend/tensorflow/optimizer.py\", line 135, in _distributed_tf_update_step\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/backend/tensorflow/optimizer.py\", line 132, in apply_grad_to_update_var\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/optimizers/adam.py\", line 148, in update_step\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/ops/numpy.py\", line 5463, in multiply\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/backend/tensorflow/sparse.py\", line 627, in sparse_wrapper\n\n  File \"/Users/karinagonzalez/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/backend/tensorflow/numpy.py\", line 497, in multiply\n\nIncompatible shapes: [9] vs. [0]\n\t [[{{node adam/Mul_23}}]] [Op:__inference_one_step_on_iterator_214819]\n"}